# Generated by Django 4.2.10 on 2024-02-25 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_remove_shop_product_id'),
        ('LocalMarket', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('0', 'Cancelled'), ('1', 'Placed'), ('2', 'Shipped'), ('3', 'Delivered')], default='1', max_length=1)),
                ('total_amount', models.FloatField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.shop')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalMarket.customer')),
            ],
        ),
    ]
