# Generated by Django 4.2.10 on 2024-03-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0004_alter_shop_gst_no'),
        ('LocalMarket', '0006_rename_quantity_orderitem_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vendor.shop'),
        ),
    ]
