# Generated by Django 4.2.10 on 2024-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0007_rename_amount_product_price_product_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
