# Generated by Django 4.2.10 on 2024-03-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0009_remove_product_category_name_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LocalMarket.orderitem'),
        ),
    ]
