# Generated by Django 4.2.10 on 2024-03-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0010_remove_orderitem_order_id_order_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='OrderItem_id',
            new_name='orderItem_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zip_code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LocalMarket.order'),
        ),
    ]
