# Generated by Django 4.2.10 on 2024-03-03 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0011_rename_orderitem_id_orderitem_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
