# Generated by Django 4.2.3 on 2024-03-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0014_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='userprofiles/user-default.png', null=True, upload_to='userprofiles/'),
        ),
    ]
