# Generated by Django 4.2.10 on 2024-03-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0016_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='shoppics/groceryShop.jpeg', null=True, upload_to='shoppics/'),
        ),
    ]
