# Generated by Django 4.2.10 on 2024-03-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0018_product_model_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='shoppics/vendorShop.jpeg', null=True, upload_to='shoppics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Lb', 'Lb'), ('Ltr', 'Ltr'), ('Each', 'Each')], default='Kg', max_length=14),
        ),
    ]
